### ISSUE TITLE
Parse result is not correct for Chrome's UA

### ISSUE THREAD

**Issue by iamamac** [cheung-chifung/UASparser-for-Python#1]
from uasparser import UASparser
uas_parser = UASparser()
result = uas_parser.parse('Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/528.11 (KHTML, like Gecko) Chrome/2.0.157.0 Safari/528.11')
# result['ua_family'] will be 'Safari'

**Comment by HicroKee** [comment]
Please update the latest version,and delete the cache file before use.
